version: '3.6'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - 'mongo:/data/db'

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: API-Shortner
    depends_on:
      - mongo
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortner
      - PORT=5000
      - HOST='http://localhost:5000/'
    volumes:
      - .:/app
volumes:
  .:
  mongo:
